<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Option1_checkBoxOption1</name>
   <tag></tag>
   <elementGuidId>b5289f53-e626-4935-a6cf-400ca9abaeb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBoxOption1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxOption1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf9ffdd1-6309-4889-8deb-8af0d4dacd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxOption1</value>
      <webElementGuid>17d57b7d-d1f3-4ae8-baf4-b6b0301a4ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>option1</value>
      <webElementGuid>33ad9ab9-68cf-4240-ad92-860b11f823c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxOption1</value>
      <webElementGuid>02dd98f5-4820-4230-9596-45fec16b10de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6114278c-f316-4539-815b-684bee5745e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxOption1&quot;)</value>
      <webElementGuid>83028f73-2815-491b-9662-da0d0713ef73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxOption1']</value>
      <webElementGuid>086e8e76-25c4-4454-977c-0a859dc6ecb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox-example']/fieldset/label/input</value>
      <webElementGuid>fbc19440-6b9d-4165-aca7-c1b78c7bd960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/label/input</value>
      <webElementGuid>6e8c0fe7-9447-462b-890d-92fe3a0969d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkBoxOption1' and @name = 'checkBoxOption1' and @type = 'checkbox']</value>
      <webElementGuid>81f97256-e3ab-437d-9e0b-e244d88d102d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
