<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio1_radioButton</name>
   <tag></tag>
   <elementGuidId>399cb2d5-7d0c-4871-b52e-5aaba4a8e122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radioButton&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radioButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d1f4434-5495-4a14-acfd-318675c9306b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>radio1</value>
      <webElementGuid>9543b52f-a0c3-43c4-85d4-9c999d3e8250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioButton</value>
      <webElementGuid>decadfbe-a154-47ab-8c24-6162eb29cbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioButton</value>
      <webElementGuid>9619c2b2-c99f-4f06-9808-d1c111828de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2df2b128-6e3c-4e5f-8882-38f055b7e6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-example&quot;)/fieldset[1]/label[1]/input[@class=&quot;radioButton&quot;]</value>
      <webElementGuid>38066cd6-6d3f-4865-8f44-5fb2439e8e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radioButton']</value>
      <webElementGuid>d1727fbf-b576-420b-ad55-8a42877e6dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radio-btn-example']/fieldset/label/input</value>
      <webElementGuid>26be01fc-0f73-4c66-a97f-3d32940a5c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58af82fa-9340-4c5a-a68c-1308bd4573a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radioButton' and @type = 'radio']</value>
      <webElementGuid>3c8b7eb4-d494-4df5-809f-39a7213694f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
