<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Radio Button Example</name>
   <tag></tag>
   <elementGuidId>ed8bd1a6-2450-471b-9c9f-b3eabcefeee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>legend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radio-btn-example']/fieldset/legend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>ceb9bd3d-5adc-4d5d-91af-6a0085adc875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Radio Button Example</value>
      <webElementGuid>0bfc7e1c-afd6-46cd-b1b2-33c943a17ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-example&quot;)/fieldset[1]/legend[1]</value>
      <webElementGuid>1720ec9a-4847-4514-92c3-bfbb5b1c5f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radio-btn-example']/fieldset/legend</value>
      <webElementGuid>116377f4-a2c3-4e14-aabc-9b5ed9f598d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Page'])[2]/following::legend[1]</value>
      <webElementGuid>42528f21-0854-4391-aedf-c5dc5d3daa54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signup'])[1]/following::legend[1]</value>
      <webElementGuid>0a37353b-cddc-4e0e-bcfa-7535f7b5de9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Radio Button Example']/parent::*</value>
      <webElementGuid>2512c3f5-988c-40a5-a68b-69778acb355e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//legend</value>
      <webElementGuid>7647ca1b-7c4b-47e0-a4dd-892074ea280f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[(text() = 'Radio Button Example' or . = 'Radio Button Example')]</value>
      <webElementGuid>90b49b34-6a52-4e74-8dd6-dd6d94bd2769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
