<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Suggession Class Example</name>
   <tag></tag>
   <elementGuidId>20d31652-578f-4801-91f4-487ec412b084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-class-example > fieldset > legend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select-class-example']/fieldset/legend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>7e18e6f8-376c-469e-a77d-691179254218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suggession Class Example</value>
      <webElementGuid>9d3df9c2-67bc-4379-b9d0-31ce79c4c59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-class-example&quot;)/fieldset[1]/legend[1]</value>
      <webElementGuid>8ab0cd96-99e6-4438-88e9-1017e666cb8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-class-example']/fieldset/legend</value>
      <webElementGuid>1aa5cea7-1ac4-47d1-aac5-498163a5c2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Example'])[1]/preceding::legend[1]</value>
      <webElementGuid>7350355b-b361-470f-a9c0-51a95b84b617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox Example'])[1]/preceding::legend[2]</value>
      <webElementGuid>138eca8b-d69f-4607-b80a-d75d0d5b74b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suggession Class Example']/parent::*</value>
      <webElementGuid>7e2f7c2e-aaf9-4d10-83d7-6b51fa88b469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/legend</value>
      <webElementGuid>f2973aa1-8b56-4147-8dd4-894b9be4ab68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[(text() = 'Suggession Class Example' or . = 'Suggession Class Example')]</value>
      <webElementGuid>7bfa6f27-b8e5-4278-b961-59bbc3697ab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
