<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                     Option1                    Option2                    Option3</name>
   <tag></tag>
   <elementGuidId>d2817f03-e8d9-4802-b070-f5724ce4b689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdown-class-example</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown-class-example']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>980ad8c0-d636-4915-985e-67ce4f125a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>d57d223b-0d8f-4f62-8e0e-f17256eba646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dropdown-class-example</value>
      <webElementGuid>f0353e5a-cb19-4a5e-8617-33d636324474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Select
                     Option1
                    Option2
                    Option3
                </value>
      <webElementGuid>9c9b0f2b-6c86-44f7-971a-13941a9558a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-class-example&quot;)</value>
      <webElementGuid>dc728483-55da-470f-aba0-5bd6311298a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown-class-example']</value>
      <webElementGuid>41f0282e-08f4-49c4-86df-1eaba0408ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Example'])[1]/following::select[1]</value>
      <webElementGuid>63dd7d52-dea2-4f39-ada0-510a42fb5fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggession Class Example'])[1]/following::select[1]</value>
      <webElementGuid>da8175bf-6d4e-4637-b952-916b5bcac3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkbox Example'])[1]/preceding::select[1]</value>
      <webElementGuid>fdb493b8-40a5-4fe8-a484-3524f6278381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a7020e5f-918a-4171-89b1-3b37a7a634db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown-class-example' and @name = 'dropdown-class-example' and (text() = '
                     Select
                     Option1
                    Option2
                    Option3
                ' or . = '
                     Select
                     Option1
                    Option2
                    Option3
                ')]</value>
      <webElementGuid>08dc2948-bac2-4647-add6-b58d87c3074a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
